hl.on("hyprland.start", function()
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/development/scripts/wallpaper_daemon.sh")
end)
