monitor = DP-2, 2560x1440@144, 0x0, 1
monitor = DP-1, 2560x1440@60, 2560x0, 1

# flip default workspace cause of stupid display ports order
workspace = 1, monitor:DP-2, default:true
workspace = 5, monitor:DP-1, default:true
